language: android
jdk: oraclejdk8
dist: trusty
sudo: required

cache:
  yarn: true
  directories:
    - node_modules

android:
  components:
    - build-tools-28.0.3
    - android-28

before_install:
  - nvm install 10
  - node --version
  - npm install -g yarn
  - chmod +x ./android/gradlew

install:
  - yarn install

script:
  - yarn lint
  - yarn test
  - cd android && ./gradlew bundleRelease
